name: dopos_print
description: "The dopos_print plugin is a Flutter plugin designed to interface with thermal printers on Windows. This plugin enables Flutter applications to list available thermal printers and send print jobs to a selected printer. The plugin supports printing text and images using JSON-formatted print instructions, allowing for flexible and customizable print layouts. It leverages the native Windows printing capabilities through a C++ backend to ensure reliable and efficient printing operations."
version: 0.0.4
homepage: https://github.com/skabdulnasim

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DoposPrintPluginCApi
      android:
        package: com.softwebfashion.dopos_print
        pluginClass: DoposPrintPlugin